### ISSUE TITLE
Can't verify self-signed certificates

### ISSUE THREAD

**Issue by bill-myers** [paulcbetts/ModernHttpClient#114]
This project contains this gem on iOS:
 if (serverCertChain.Count == 1) {
errors = SslPolicyErrors.RemoteCertificateChainErrors;
goto sslErrorVerify;
}

And the "goto" skips initialization of the certificate parameter, so that the app can't verify it...

Obviously the main use case of this feature is for self-signed certificates, which of course have a chain size of 1...

Same enlightened behavior on Android.

**Comment by paulcbetts** [comment]
Hey guys, I decided to make this a paid feature, check here for more info:

http://log.paulbetts.org/modernhttpclient-pro-edition/
