### ISSUE TITLE
How to use with RestSharp?

### ISSUE THREAD

**Issue by tkowalczyk** [paulcbetts/ModernHttpClient#117]
Hi,
It is possible to use this library with RestSharp in Xamarin based project?

Best,
Tomek

**Comment by Cheesebaron** [comment]
If RestSharp somehow allows to use the handlers ModernHttpClient implements, then yes.

**Comment by paulcbetts** [comment]
@tkowalczyk RestSharp doesn't use HttpClient, it is a precursor to HttpClient; there's no way at the moment to use it, sorry :(

**Comment by ghuntley** [comment]
@tkowalczyk use Refit + Fusillade instead https://github.com/paulcbetts/refit + https://github.com/paulcbetts/Fusillade

**Comment by tkowalczyk** [comment]
@ghuntley thx for this!

**Comment by ghuntley** [comment]
@tkowalczyk nps check out this https://gist.github.com/ghuntley/ed2eb754a47e2cd3bc90 as well.

**Comment by ghuntley** [comment]
@tkowalczyk last one I swear, came across this super compelling example @  http://arteksoftware.com/resilient-network-services-with-xamarin/

**Comment by tkowalczyk** [comment]
@ghuntley this is really great, have to digg into ;)

**Comment by adamfisher** [comment]
https://github.com/FubarDevelopment/restsharp.portable/issues/34
