### ISSUE TITLE
Support for Cookies

### ISSUE THREAD

**Issue by pmoran1947** [paulcbetts/ModernHttpClient#118]
How do you configure the ModernHttpClient to support cookies. I cant see how to do it.

**Comment by paulcbetts** [comment]
@pmoran1947 There isn't any explicit support for cookies, you need to do it by-hand (cookies are just an HTTP header)

**Comment by robertbird** [comment]
Hi @paulcbetts,

I have to say I am also struggling with this. I have tried following your advice here https://github.com/paulcbetts/ModernHttpClient/issues/54 by manually creating a request and then setting the "Cookie" header. 

But it seems like the HttpClient is removing my header when the name is "Cookie". If I set the name to anything else I see the header in fiddler, but when the name is cookie then no header appears. (I am using the Microsoft.Net.Http nuget package version 2.2.28 for the client and testing this via a unit test). 

Any advice would be appreciated!

Cheers,
Rob

P.S I'm loving all of your libraries (Akavache, Fusillade and trying to get my head around ReactiveUI!), thanks for all the hard work, amazing stuff.

**Comment by paulcbetts** [comment]
@robertbird Hm, if HttpClient is filtering headers, this might change my stance on this bug. Can you create a PR that modifies Playground to show the bug? (http://httpbin.org is super useful as a server here)

**Comment by robertbird** [comment]
Cheers for the quick response, as with most things, 20 mins later on google and SO had the answer.

http://stackoverflow.com/questions/12373738/how-do-i-set-a-cookie-on-httpclients-httprequestmessage/13287224#13287224

So by default HttpClient will indeed filter out this header. But if you set UseCookies to false then it works. 
So I am now using:
    var client = HttpClientFactory.Create(new NativeMessageHandler { UseCookies = false })
and then adding the cookie:
    client.DefaultRequestHeaders.Add("Cookie", string.Format("{0}={1}", myKey, myValue));

So it is all working as expected now. 

Thanks again!
Rob

**Comment by paulcbetts** [comment]
:cool:, thanks

**Comment by paulcbetts** [comment]
Fixed!

**Comment by trevoriancox** [comment]
I derive a class PersistentCookieHandler from NativeCookieHandler, and pass that in:

{{{
    public RestClient() : base(new NativeMessageHandler(false, customSSLVerification, PersistentCookieHandler.Instance))
         {
             PersistentCookieHandler.Instance.Load();
}}}

On iOS, this loads the cookies from NSHttpCookieStorage.SharedStorage.
