### ISSUE TITLE
use with ServiceStack (Xamarin) ?

### ISSUE THREAD

**Issue by ajonno** [paulcbetts/ModernHttpClient#122]
hi Paul, is it possible for me to use ModernHttpClient with ServiceStack client ?

cheers
Angus

**Comment by paulcbetts** [comment]
Why not?

**Comment by ajonno** [comment]
wow that was quick! im only just getting started/familiar w/ ServiceStack. How would I instantiate / make the reference to ModernHttpClient via ServiceStack ?

**Comment by paulcbetts** [comment]
I have no idea, you should read the ServiceStack docs :)

**Comment by ghuntley** [comment]
Pretty sure ServiceStack does not use Microsoft.Net.Http thus if this is the case then it won't work as ModernHttpClient is just a custom driver/HttpClientHandler.

**Comment by ajonno** [comment]
yea thanks, ive been digging through the docs etc.. for the benefits modernhttpclient lends im happy to stick w/ HTTPClient

**Comment by mzekrallah** [comment]
This has been added now to ServiceStack 

https://forums.servicestack.net/t/xamarin-system-net-vs-native-nsurlsession-performance-in-servicestack/921
