### ISSUE TITLE
Please add a better example

### ISSUE THREAD

**Issue by dshirley** [paulcbetts/ModernHttpClient#129]
This shows how to instantiate an object.  It doesn't show how to perform an http request.
var httpClient = new HttpClient(new NativeMessageHandler());

I think it can be improved by show how to do a GET.
Ideally I wan't to copy & paste the example code into my app and compile and run it with no more than 1 second of effort.

The example app unfortunately doesn't meet this requirement either because the code that instantiates the HttpClient is separated from the code that performs the request and it is mixed in with the UI code.

Also please include a "using" statement

**Comment by dshirley** [comment]
I'm curious.  Why close?

**Comment by Cheesebaron** [comment]
If you don't know how to use `HttpClient` then why would you even need the handlers this project provides?

**Comment by dshirley** [comment]
Just because someone isn't familiar with HttpClient doesn't mean they won't need to use networking in their app.  In my case at least, I'm intimately familiar with java networking and Obj-C networking but I don't want two code bases for networking.

I did look through the example app, but I found it fairly challenging to navigate.  To no fault of your own, Xamarin Studio for some reason won't let me command click through to the definition of the AppDelegate class in your project.  Regardless, the main.cs file is almost always reserved for a one line main function in iOS projects.  In the ModernHttp example, that's where the AppDelegate is located (it's almost always in its own file in iOS projects).  In addition, the AppDelegate is being used as an MVC controller which is also atypical.  I'm way more familiar with iOS and Xamarin, so maybe iOS conventions just aren't used in Xamarin much.  The sum of these issues made it far less clear than a simple 5 line example that can be copy/pasted verbatim.  The 5 line example that I gave is spread across two files in the sample app, and due to my trouble finding things I got frustrated and looked at the MS docs instead.

Thanks for the reply.  It's no skin off my back if you don't want to use this.  I was just curious of your thinking.

**Comment by Yortw** [comment]
I'm inclined to agree the existing readme/sample is good. It clearly shows how (easy it is) to integrate *modern http client*. If you need to know how to use HTTP client in the first place then you should read the MS docs. Adding that info here clutters up the sample with stuff not directly related to the use of this library and risks missing detail about http client's usage (such as reusing long lived instances to help with connection pooling). The MS docs already do a good job of that, so why repeat it? Perhaps a link to a good MS doc or blog post could be included for people who have some how arrived here first without already understanding HTTP client? A link like that might be a good compromise? Just my 2 cents.
