### ISSUE TITLE
Windows Phone?

### ISSUE THREAD

**Issue by Yortw** [paulcbetts/ModernHttpClient#131]
Would you accept a pull request that contained a WP project with a native handler implementation that enabled compression by default? 

I believe the ModernHttpClient handlers for iOS  and Android enable compression by default (?) and it's annoying in Xamarin projects to have to manually write the (2 lines of) code just for WP to turn compression on. Being able to treat WP the same as the other two platforms when using ModernHttpClient makes sense to me.

I don't think there's (currently) anything else worth putting in a WP version, so some might see this as overkill which is why I ask.

Thanks.

**Comment by paulcbetts** [comment]
I would not consider that PR, sorry that Microsoft sucks. People should just add the two lines.
