### ISSUE TITLE
ReasonPhrase not returned properly on iOS

### ISSUE THREAD

**Issue by marktaling** [paulcbetts/ModernHttpClient#135]
In the iOS implementation the ReasonPhrase is not returned, it always returns the default string for the statuscode.

This has been fixed previously for the android issue: #64

**Comment by marktaling** [comment]
I tried to fix the issue myself but apparently the framework doesn't support it. The ReasonPhrase is nowhere to be found on the NSHttpUrlResponse :-(

**Comment by Cheesebaron** [comment]
Check this: https://github.com/AFNetworking/AFNetworking/issues/544#issuecomment-8941909

**Comment by paulcbetts** [comment]
Looks like this isn't possible on iOS, sorry :(
