### ISSUE TITLE
Does ModernHTTPClient apply to dependencies?

### ISSUE THREAD

**Issue by paulyoung** [paulcbetts/ModernHttpClient#138]
If I write a PCL using `System.Net.Http` and a consumer adds that and ModernHTTPClient, will that affect the calls made within the PCL?

**Comment by paulcbetts** [comment]
ModernHttpClient is simply an HttpMessageHandler, it doesn't do some kind of global registration to change how HttpClient works. If you pass in a HttpClient to your PCL that has ModernHttpClient already set up (i.e. the snippet in https://github.com/paulcbetts/ModernHttpClient#usage), it'll definitely work.

**Comment by paulyoung** [comment]
That makes sense. Thanks!
