### ISSUE TITLE
GetCookies / Cookies property (v 2.3.0)

### ISSUE THREAD

**Issue by epetutsc** [paulcbetts/ModernHttpClient#139]
HI, 

new NativeCookieHandler().GetCookies() raises exception:
<pre>
Missing method ModernHttpClient.NativeCookieHandler::GetCookies() in assembly ModernHttpClient.dll
</pre>

Facade and Android/iOS implementations are different. Facade has GetCookies() method. Native implementations have Cookies property

*Facade:*
<pre>
    public class NativeCookieHandler
    {
        [...]
        public Cookie[] GetCookies()
        {
            throw new Exception(wrongVersion);
        }
    }
</pre>

*Android:*
<pre>
    public class NativeCookieHandler
    {
        [...]
        public ICollection<Cookie> Cookies
        {
            get 
            {
                return cookieManager.CookieStore.Cookies.Select(ToNetCookie).ToList();
            }
        }
    }
</pre>

*iOS:*
<pre>
    public class NativeCookieHandler
    {
        [...]
        public ICollection<Cookie> Cookies
        {
            get 
            {
                return NSHttpCookieStorage.SharedStorage.Cookies.Select(ToNetCookie).ToList();
            }
        }
    }
</pre>

**Comment by paulcbetts** [comment]
hwhoops, can you make a PR to fix this?
