### ISSUE TITLE
Errors with error domain of kCFErrorDomainCFNetwork not handled properly

### ISSUE THREAD

**Issue by Tableau-David-Potter** [paulcbetts/ModernHttpClient#146]
We're getting errors with an error domain of `kCFErrorDomainCFNetwork`.  These errors cause an exception of type Exception to get thrown which means the app has no practical way of handling them.  One such error has a code of 310 which maps to `kCFErrorHTTPSProxyConnectionFailure` in the `CFNetworkErrors` enum.  None of these symbols appear to be mapped into C#.  I see how to fix this and I'd rather not define these symbols myself.  Any ideas?

Thanks,
***David***

**Comment by Tableau-David-Potter** [comment]
I submitted a [pull request](https://github.com/paulcbetts/ModernHttpClient/pull/148) which Paul has accepted that addresses this.  Thanks Paul.

**Comment by paulcbetts** [comment]
Fixed!
