### ISSUE TITLE
Missing method when using ResponseHeadersRead and CancellationToken

### ISSUE THREAD

**Issue by molinch** [paulcbetts/ModernHttpClient#149]
With latest ModernHttpClient 2.4.0, when using GetAsync with HttpCompletionOption.ResponseHeadersRead and a CancellationToken I get a missing method exception.

Screenshot can be found here: http://prntscr.com/7073il

Stacktrace is
<pre>[Mono] Assembly Ref addref ModernHttpClient[0xb7a22168] -> System.Core[0xb7bf5ff0]: 11
[] Missing method Android.Runtime.JNIEnv::CallObjectMethod(intptr,intptr,JValue*) in assembly Mono.Android.dll, referenced in assembly /storage/emulated/0/Android/data/com.hager.mediaviewergroup/files/.__override__/OkHttp.dll</pre>

**Comment by peterno** [comment]
I am getting this aswell when using it with SignalR and 2.4.0. I tried to change back the OkHttp.dll to the one in 2.3.0 but that gave other errors with the Builder.

My linkersettings is None and i am using Xamarin.Andriod: 4.20.2.1 and Xamarin 3.9.547.0 in Visual Studio.

I have to switch back to 2.3.0 and my own fork of the Android version.

Stacktrace is:
```
Exception: System.MissingMethodException: Method not found: 'Android.Runtime.JNIEnv.CallObjectMethod'.
  at ModernHttpClient.NativeMessageHandler+<SendAsync>c__async0.MoveNext () [0x00154] in /Users/paul/code/paulcbetts/modernhttpclient/src/ModernHttpClient/Android/OkHttpNetworkHandler.cs:96 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
  
```

**Comment by paulcbetts** [comment]
This appears to be some weirdo glitch because I use Xamarin Studio's Alpha channel to build everything. I'm going to roll a new release tonight built against standard channel.

**Comment by paulcbetts** [comment]
@molinch @peterno Can you guys try to update to the latest stable Xamarin.Studio / Xamarin.Android? 

http://forums.xamarin.com/discussion/37276/stable-release-xamarin-studio-5-9-0-new-features-and-bug-fixes/p1

**Comment by molinch** [comment]
Hi Paul
I am using pre-last one. Our team tried the last and it was too much pain:
bugs in Xam.iOS, bugs in XS (quick search crashes XS...). So we can't do
that yet.

Therefore I can make a quick test and tell you if it solves issue (then I
will revert to previous).

**Comment by peterno** [comment]
Hi,

 

Unfortunately I cannot test now, we are in the release phase and start the systems tests on Friday, and looking at the issues a lot of people have had with the latest stable release I guess we will have to wait a couple of weeks until our release is approved.

 

Paul, is there any possibility that you could downgrade and build a release from that? I guess there might be many users staying on the pre-last stable release but still wanting to use the latest ModernHttpClient as they do not know that you have built it using the latest.

 

Best regards,

/Peter

 

Från: Fabien Molinet [mailto:notifications@github.com] 
Skickat: den 6 maj 2015 07:23
Till: paulcbetts/ModernHttpClient
Kopia: Peter Norman
Ämne: Re: [ModernHttpClient] Missing method when using ResponseHeadersRead and CancellationToken (#149)

 

Hi Paul
I am using pre-last one. Our team tried the last and it was too much pain:
bugs in Xam.iOS, bugs in XS (quick search crashes XS...). So we can't do
that yet.

Therefore I can make a quick test and tell you if it solves issue (then I
will revert to previous).

**Comment by paulcbetts** [comment]
> Paul, is there any possibility that you could downgrade and build a release from that? I guess there might be many users staying on the pre-last stable release but still wanting to use the latest ModernHttpClient as they do not know that you have built it using the latest.

@peterno, you can manually modify your NuGet package.config to not allow upgrades past a certain version, check out https://docs.nuget.org/create/versioning

**Comment by peterno** [comment]
Hi,

What I meant was that many users like me stay on the current Xamarin stable release but upgrade to the latest ModernHttpClient and get those errors. Of course one can downgrade the ModernHttpClient again but then would miss out on the new features.

Unfortunately the new stable Xamarin release is not stable enough for us.

Thanks for all your great work,
/Peter

Skickat från min Windows Phone
________________________________
Från: Paul Betts<mailto:notifications@github.com>
Skickat: ‎2015-‎05-‎06 21:41
Till: paulcbetts/ModernHttpClient<mailto:ModernHttpClient@noreply.github.com>
Kopia: Peter Norman<mailto:peter.norman@live.com>
Ämne: Re: [ModernHttpClient] Missing method when using ResponseHeadersRead and CancellationToken (#149)

> Paul, is there any possibility that you could downgrade and build a release from that? I guess there might be many users staying on the pre-last stable release but still wanting to use the latest ModernHttpClient as they do not know that you have built it using the latest.

@peterno, you can manually modify your NuGet package.config to not allow upgrades past a certain version, check out https://docs.nuget.org/create/versioning

---

**Comment by paulcbetts** [comment]
@peterno Sorry, I can't package one-off versions like that officially - you can certainly build the library yourself though!

**Comment by molinch** [comment]
Fixed in new Nugets
