### ISSUE TITLE
Crash in iOS 6 on `new ModernHttpClient.NativeMessageHandler()`

### ISSUE THREAD

**Issue by patridge** [paulcbetts/ModernHttpClient#151]
I've got an app where we recently decided to upgrade our HttpClient code to use ModernHttpClient. Unfortunately, it is still supporting back to iOS 6 and when I finally tested it on a device, it crashed. I am deploying to an iPhone 4S running iOS 6.1.3 (the last of my test devices capable of testing iOS 6). This first happened with v2.3.0, but also occurs with v2.4.0.

If I am reading the stack trace correctly (below), it appears to crash with [this `NSUrlSession.FromConfiguration` call](https://github.com/paulcbetts/ModernHttpClient/blob/38d88569842caa178d7758aa21c609927ce19e2a/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs#L56).

I will try to work directly from source in the next 12 hours to debug the device directly to that line in action to see if I can glean anything useful, but I wanted to toss this out first since I wasn't even sure iOS 6 is supposed to be supported.

Here is a sample stack trace leading back in to :

> Top-level exception: System.ArgumentNullException: Argument cannot be null.
> Parameter name: configuration
> at Foundation.NSUrlSession.FromWeakConfiguration (Foundation.NSUrlSessionConfiguration configuration, Foundation.NSObject weakDelegate, Foundation.NSOperationQueue delegateQueue) [0x00011] in /Users/builder/data/lanes/1503/6481535e/source/maccore/src/build/ios/native/Foundation/NSUrlSession.g.cs:604
> at Foundation.NSUrlSession.FromConfiguration (Foundation.NSUrlSessionConfiguration configuration, Foundation.NSUrlSessionDelegate sessionDelegate, Foundation.NSOperationQueue delegateQueue) [0x00000] in /Users/builder/data/lanes/1503/6481535e/source/maccore/src/build/ios/native/Foundation/NSUrlSession.g.cs:595
> at ModernHttpClient.NativeMessageHandler..ctor (Boolean throwOnCaptiveNetwork, Boolean customSSLVerification, ModernHttpClient.NativeCookieHandler cookieHandler) [0x00039] in /Users/paul/code/paulcbetts/modernhttpclient/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs:56
> at ModernHttpClient.NativeMessageHandler..ctor () [0x00000] in /Users/paul/code/paulcbetts/modernhttpclient/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs:53
> at SomeApp.RequestManager..ctor (...) [0x00096] in /Users/.../RequestManager.cs:75
> at SomeApp.AppDelegate..ctor () [0x0004e] in /Users/.../AppDelegate.cs:129

**Comment by paulcbetts** [comment]
NSUrlSession was added in iOS 7.0, you need to use ModernHttpClient 1.x if you want to support iOS 6.0

**Comment by patridge** [comment]
Thanks for the response. I'll just rig up iOS 6 systems to use the vanilla .NET HttpClientHandler instead and see if that gives us any trouble. Short of losing all the gains ModernHttpClient and Fusillade is going to provide going forward (thank you so much for them both!!), at least I can keep them along for the ride a little longer.
