### ISSUE TITLE
System.OutOfMemoryException when uploading large file

### ISSUE THREAD

**Issue by barquehk** [paulcbetts/ModernHttpClient#154]
I am testing the maximum size of file that ModernHttpClient could handle. When I am trying to use this client to upload file that is 512MB on iPhone4s iOS 8.3 simulator, the app crashed with OutOfMemoryException.

````
error : System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) object:__icall_wrapper_mono_array_new_specific (intptr,int)
  at System.IO.MemoryStream.ToArray () [0x00018] in /Users/builder/data/lanes/1503/13d1cdc2/source/mono/external/referencesource/mscorlib/system/io/memorystream.cs:589 
  at ModernHttpClient.NativeMessageHandler+<SendAsync>c__async0.MoveNext () [0x0010e] in /Users/reeve/sandbox/ModernHttpClient/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs:111 
````
This is the line where the exception was thrown. It appears that the system doesn't have enough memory to convert the stream into an array. In the case, the stream should be equal or slightly larger than 512MB (since it is actually a MultipartFormDataContent Stream)
````csharp
                Body = NSData.FromArray(ms.ToArray()),
````
The link below goes to the file that the line above come from.
https://github.com/paulcbetts/ModernHttpClient/blob/master/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs#L101-111

When I was trying to look for a solution, I was end up on this stackoverflow question.
http://stackoverflow.com/questions/27427731/nsurlsession-createuploadtask-failure-with-xamarin-ios

The solution is to write the content stream to a temp file before creating the session task. Then I did a small change on SendAsync
````csharp
var headers = request.Headers as IEnumerable<KeyValuePair<string, IEnumerable<string>>>;
string tempFile = Path.GetTempFileName();
using (var ms = System.IO.File.Open (tempFile,FileMode.OpenOrCreate)) {
	if (request.Content != null) {
		await request.Content.CopyToAsync (ms).ConfigureAwait (false);
		headers = headers.Union (request.Content.Headers).ToArray ();
	}
}

NSInputStream file = new NSInputStream (tempFile);

var rq = new NSMutableUrlRequest() {
    AllowsCellularAccess = true,
    /*Body = NSData.FromArray(ms.ToArray()),*/
	BodyStream = file,
    CachePolicy = (!this.DisableCaching ? NSUrlRequestCachePolicy.UseProtocolCachePolicy : NSUrlRequestCachePolicy.ReloadIgnoringCacheData),
    Headers = headers.Aggregate(new NSMutableDictionary(), (acc, x) => {
        acc.Add(new NSString(x.Key), new NSString(String.Join(getHeaderSeparator(x.Key), x.Value)));
        return acc;
    }),
    HttpMethod = request.Method.ToString().ToUpperInvariant(),
    Url = NSUrl.FromString(request.RequestUri.AbsoluteUri),
};
````
The code change successfully uploads a 512MB file on first gen iPad Mini.

But it looks kind of silly to have a temp file before sending out the actual content and it may not work on those devices that have very limited of storage...

**Comment by paulcbetts** [comment]
You should directly use NSUrlSession's background upload, uploading a 500MB file using ModernHttpClient is a bad idea
