### ISSUE TITLE
Missing method while executing GetAsync in Xamarin.Android with OKHttp

### ISSUE THREAD

**Issue by vhugogarcia** [paulcbetts/ModernHttpClient#155]
I'm getting the following error when calling GetAsync() Method.

```
Missing method Android.Runtime.JNIEnv::CallObjectMethod(intptr,intptr,JValue*) in assembly Mono.Android.dll, referenced in assembly OkHttp.dll
```

Settings of my project: 
Minimum Android Version: Android 4.0 (API Level 14)
Target Android Version Android 4.4 (API Level 19)

All permissions are set.

Xamarin.Android
Version: 4.20.2.1
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Xamarin Studio
Version 5.8.3 (build 1)

ModernHttpClient version: 2.4.1

any idea or workaround is always welcome.

**Comment by paulcbetts** [comment]
You need to update to the latest version of Xamarin.Android
