### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by wesoos** [paulcbetts/ModernHttpClient#157]
Hi,

I'm getting an error when using this ModernHttpClient., when calling GetAsync

method not found: android.runtime.jnienv.callobjectmethod

When I just use HttpClient() it works fine.

**Comment by paulcbetts** [comment]
Update your version of Xamarin.Android

**Comment by wesoos** [comment]
I am on the latest stable version of android

**Comment by wesoos** [comment]
Paul, any comment on this?
