### ISSUE TITLE
Preauthentication does not work

### ISSUE THREAD

**Issue by nepabrite** [paulcbetts/ModernHttpClient#160]
Hello,

This package has done wonders for curing the TLS issue with Android Mono. The only problem is: Preauthentication does not appear to work, and all requests return with 401.

**Comment by paulcbetts** [comment]
You should just set the Authorization header yourself

**Comment by robert-sayers** [comment]
Hi, 

With regarding setting the authorisation header yourself.  It appears that if you have set the header with incorrect credentials - an invalid password for example,  there appears to be two requests sent both resulting in 401.  

Scenario that I have seen is for a login to an application.  If the user has entered the password incorrectly there appears to be two requests being sent both with the header information populated.  Is this a potential issue or is there a setting or method that I've missed?
