### ISSUE TITLE
Is it possible to use this for large files (+500MB) and still moniter the progress??

### ISSUE THREAD

**Issue by goldsmit409** [paulcbetts/ModernHttpClient#164]
Hi
I am trying to download a large file using this.

    var messageHandler = new NativeMessageHandler ();
    var request = new HttpRequestMessage (HttpMethod.Get, url);
    messageHandler.RegisterForProgress (request, HandleDownloadProgress);
    var client = new HttpClient (messageHandler);
    var result = await client. (request);
    var fileContent = result.Content.ReadAsByteArrayAsync ();

I maybe not doing it the right way, any help is appriciated
thanks

**Comment by goldsmit409** [comment]
anyone???

**Comment by Cheesebaron** [comment]
You are not explaining whether anything is wrong or you get errors or anything. We are not mind readers.

**Comment by goldsmit409** [comment]
I am sorry i dint explain the issue well, so what happens in this that file downloads but it stays in the memory and very soon after downloading around 100 mb phone runs out of memory and the download stops. what i need to do is get a stream and save it to the file directly so nothing stays in memory...

here is what i found for a way for it to work 

       var result = await client.SendAsync (request,HttpCompletionOption.ResponseHeadersRead);
       result.EnsureSuccessStatusCode();
       using (Stream streamToReadFrom = await result.Content.ReadAsStreamAsync())
      {
	  using (Stream streamToWriteTo = File.Open(filePath, FileMode.OpenOrCreate))
	  	{
	  		byte [] data = new byte[1024];
	  		int count;
	  		long read=0;
	  		while ((count = streamToReadFrom.Read(data, 0, 1024))> 0)
	  		{
	  			read+=count;
	  			streamToWriteTo.Write(data,0,count);
                                // code to handle download progress

	  	         }
                  }

In this way i am not able to use the HandleDownloadProgress (long bytesInThisChunk, long totalBytesDownloaded, long totalBytesExpected)

also not sure if this is the right way to do it...

**Comment by paulcbetts** [comment]
You should not use ModernHttpClient _or_ HttpClient in general to download such large files on a phone, use NSUrlSession's background download feature
