### ISSUE TITLE
Gzip decompression on Xamarin.Forms / Android

### ISSUE THREAD

**Issue by dvolvenl** [paulcbetts/ModernHttpClient#198]
I have the following code to create my RestService, which resides in my Xamarin.Forms PCL:

    var handler = new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate };
    var client = new HttpClient(handler)  { BaseAddress = new Uri(Settings.BASESERVICEURL) };
    var service = RestService.For<IMyApi>(client);
    var items = await service.GetItems();

When running this on the Xamarin.Android project I get the following error:

    "Method 'HttpClientHandler.set_AutomaticDecompression' not found."

I then decided to change my code to use the ModernHttpClient, which according to all claims has some form of GZIP decompression:

      var handler = new NativeMessageHandler();

This however, leads to the following error, which essentially means that the response wasn't decompressed before it started parsing to Json:

    Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
    
My interface definition is configured with the Accept-Encoding header:

    [Headers("Accept: application/json", "Accept-Encoding: gzip")]
    public interface IMyApi

So what should be the correct way of setting this up for Xamarin Forms / Android? I verified using Fiddler that my API is actually returning a gzipped response when asked for it with the Accept-Encoding header.

**Comment by gmarrot** [comment]
I have exactly the same issue, only for Xamarin Android. It works fine with Xamarin iOS.
Have you found a solution ?

**Comment by dvolvenl** [comment]
Nope, unless you accept disabling gzip compression as a solution. Still hoping this ticket gets answered/resolved at some point in the near future.

**Comment by gmarrot** [comment]
I have found why it raises an exception. ModernHttpClient uses OkHttp as Android's client.
This client supports and decompresses GZip response automatically if we don't set an Accept-Encoding header. However, if we set the header, even with gzip value, it doesn't decompress automatically, we need to do it manually.

In all cases, if we want to support deflate compression too, we will have to do it manually for Android (iOS supports both automatically).

**Comment by ncruces** [comment]
You don't seem to be instantiating `NativeMessageHandler` (you're instantiating `HttpClientHandler` instead)?

**Comment by paulcbetts** [comment]
> I have found why it raises an exception. ModernHttpClient uses OkHttp as Android's client.
This client supports and decompresses GZip response automatically if we don't set an Accept-Encoding header. However, if we set the header, even with gzip value, it doesn't decompress automatically, we need to do it manually.

^^ this is correct
