### ISSUE TITLE
iOS does not support https with self signed certificates

### ISSUE THREAD

**Issue by paul-kiar** [paulcbetts/ModernHttpClient#203]
To Reproduce:
Setup a sample https website with a self signed cert
On the iOS simulator install the certificate by dragging and dropping it on the simulator
Create a http client with the modernhttp handler
do a GetAsync on the server

Expected result: Success
Actual result: System.Net.WebException: An SSL error has occurred and a secure connection to the server cannot be made.

If you use safari on the simulator it will successfully download that url.

**Comment by Tableau-David-Potter** [comment]
You need to purchase ModernHttpClient-Pro to get this functionality.

**Comment by paul-kiar** [comment]
That's funny.  If I can't get through the red tape to get our QA servers to use real certificates (which you can get for free).  There's no way I'm going to get them to shell out the cash for a pro version.  I think I've read a book about this.
