### ISSUE TITLE
ModernHttpClient , The network connection was lost, error

### ISSUE THREAD

**Issue by jorgenstorlie** [paulcbetts/ModernHttpClient#204]
I got this error after the app is put on and off flight mode:
<Warning>: System.Net.WebException: The network connection was lost. ---> 

Steps to reproduce:
1) Turn on flight mode
2) Turn off flight mode
3) Try to get some data

The error also happen after the app is restored from background, if i has been inactive.

I use ModernHttpClient like this:

var handler = new NativeMessageHandler ();
var client = new HttpClient (handler);
System.Net.Http.HttpResponseMessage responseMsg = await client.GetAsync (url);
responseMsg.EnsureSuccessStatusCode ();
responseBody = responseMsg.Content.ReadAsStringAsync ();
returnvalue = responseBody.Result;

Do someone have the same problem?
Any solution?

Jørgen

**Comment by jorgenstorlie** [comment]
Some more  info:

It may be a bug in IOS:

http://stackoverflow.com/questions/25372318/error-domain-nsurlerrordomain-code-1005-the-network-connection-was-lost

http://www.pluchon.com/forum/viewtopic.php?id=36

workaround;

1)
Increase the timeout parameter of the server above 30 seconds. It looks like iOS is always behaving as if the server will keep the connection open for 30 seconds regardless of the value provided in the Keep-Alive header. (This can be done for Apache by setting the KeepAliveTimeout option.
2)
You can simply disable the keep alive mechanism for iOS clients based on the User-Agent of your app (e.g. for Apache: BrowserMatch "iOS 8." nokeepalive in the mod file setenvif.conf)

I have not changed the server, it would be best to fix the client.

Someone having the same problem?

**Comment by jorgenstorlie** [comment]
it was a problem with the server

**Comment by bengibagci** [comment]
@jorgenstorlie hi, I have the same problem. I couldn't solve this problem with Keep-Alive header. How did you solve this problem?
