### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by pauldotknopf** [paulcbetts/ModernHttpClient#21]
Currently the timeout isn't being used.

http://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx

Does AFNetworking support requests with a timeout?

**Comment by habermeier** [comment]
I think there is a timeout issue with the iOS implementation:

```
			var httpClient = new HttpClient(new NativeMessageHandler()) { 
				BaseAddress = BaseUrl,
				Timeout = TimeSpan.FromSeconds(59)
			};
```

The above will throw a Task Cancellation Exception:
```
System.Threading.Tasks.TaskCanceledException: The Task was canceled
```

But this will throw a NSURLErrorDomain Timeout Error (-1001):

```
			var httpClient = new HttpClient(new NativeMessageHandler()) { 
				BaseAddress = BaseUrl,
				Timeout = TimeSpan.FromSeconds(61)
			};
```

Which results in:
```
The operation couldn’t be completed. (NSURLErrorDomain error -1001.)
```

The docs say:
> 
> NSURLErrorTimedOut
> Returned when an asynchronous operation times out.
> 
> NSURLConnection will send this error to its delegate when the timeoutInterval in NSURLRequest expires before a load can complete.
> 
> Available in OS X v10.2 and later.

The default timeout value is 60 seconds:

> The default cache policy is NSURLRequestUseProtocolCachePolicy and the default timeout interval is 60 seconds.

If you wanted to rely on a CancellationToken, you'd probably want to set the iOS.

So unless I'm missing something, on iOS your max allowed timeout is the default setting in iOS.  Granted 60 seconds should be just fine -- but if you're running a known long http request in the background (ie: not blocking UI on it), then perhaps there could be a valid use-case to be allowed to increase the timeout above the 60 second limit.

Thoughts?  I can work around this issue... but it would be nice if it could be set by user code.

**Comment by paulcbetts** [comment]
@habermeier If you're doing things that can take more than 60 seconds, you shouldn't be doing it with HttpClient, you should use NSUrlSession's background send feature

**Comment by habermeier** [comment]
Fair point.  I’m reworking the server side anyhow.  60 seconds is silly.  

Having said that, I’d hate to write a bunch of extra code for some HTTP requests that might take more than 60 seconds (out of principle).  It would be nice if I could just say — "Hey this one request — give it a 5 minute timeout, and I don’t care that much if it’s not optimal resource usage.”  

Just sayin’…

**Comment by danmiser** [comment]
I'm hitting the same 60 second timeout using modernhttpclient in my iOS app. If I comment it out, the 2 minute connection comes back as expected. Given that this really is a blocking call to get data synced down to the device, it's not really ideal to go background. Just another data point for you to consider adding the extended timeout capability.
