### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by MichaelRumpler** [paulcbetts/ModernHttpClient#240]
If the server certificate is self signed, then my handler for `ServicePointManager.ServerCertificateValidationCallback` receives an empty certificate. Therefore I cannot check if the response is from the correct server.

For iOS in NSUrlSessionHandler.cs, `DataTaskDelegate.DidReceiveChallenge` I moved the lines

				if (serverCertChain.Count == 1)
				{
					errors = SslPolicyErrors.RemoteCertificateChainErrors;
					goto sslErrorVerify;
				}

down directly above the `sslErrorVerify` label and this seems to work. Now root will be set and passed on.

The same code seems to be in OkHttpNetworkHandler.cs, `HostnameVerifier.verifyServerCertificate`, but I didn't test that yet.

**Comment by paulcbetts** [comment]
Self-signed certificates are a feature of ModernHttpClient Pro
