### ISSUE TITLE
Is it possible to support UWP?

### ISSUE THREAD

**Issue by reevelau** [paulcbetts/ModernHttpClient#241]

**Comment by Cheesebaron** [comment]
Why do you need an alternative HttpClientHandler on UWP?

**Comment by reevelau** [comment]
I have a PCL currently shared between iOS and Android. I would like to reuse the same PCL on a UWP project.

I have made a local project with limited features, just enough for my project, to run. It would be more convenient if there is a nuget distribution for UWP.

Or is there any simpler way to integration ModernHttpClient for UWP project? Please let me know.

**Comment by Cheesebaron** [comment]
Make a factory for creating your HttpClientHandler.

**Comment by reevelau** [comment]
Yes, that could be a way.
