### ISSUE TITLE
Using custom proxy with ModernHttpClient

### ISSUE THREAD

**Issue by paradisehuman** [paulcbetts/ModernHttpClient#256]
Hi.
Is there any way to have my custom proxy like httphandler with modernhttpclinet ? 
I must use modernhttpclient for ssl.

**Comment by Cheesebaron** [comment]
> I must use modernhttpclient for ssl.

That is a strange claim. The built in Xamarin handlers work much better than modernhttpclient in a lot of cases. Especially if you need to do TLS 1.2

**Comment by paradisehuman** [comment]
yes. i did that. thank you .
