### ISSUE TITLE
Support for GZIP'ed response?

### ISSUE THREAD

**Issue by Krumelur** [paulcbetts/ModernHttpClient#35]
According to this post http://stackoverflow.com/questions/2682483/nsurlconnection-nsurlrequest-gzip-support NSUrlRequest seems to support GZIP by adding a header:

[urlReq setValue:@"gzip" forHTTPHeaderField:@"Accept-Encoding"]

I can try this and will submit a fix if it works. However I do not know what to do with "deflate", as used in HttpClientHandler:

new HttpClient(new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate })

**Comment by acaliaro** [comment]
Hi. Is it possible to have an  example how to use ModernHttpCLient with gzip (Android and iOS with Xamarin Forms PCL)? I have't found it....
