### ISSUE TITLE
Enable using self-signed certificates for development purposes

### ISSUE THREAD

**Issue by AndreasPolito** [paulcbetts/ModernHttpClient#43]
Hi there, 

I have a Problem to use your OkHttpNetworkHandler with a Https Site

What do i wrong or is this a bug ?!?

see the code below 

``` cs
public JContainer  Login(Context context, string hardwareId, string user, string secret, string loginHash)
        {
            using (var client = new HttpClient(new OkHttpNetworkHandler()))
            {
                ServicePointManager.ServerCertificateValidationCallback = ServerCertificateValidationCallback;
                Uri uri = new Uri("URL");

                HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Post, uri);

                requestMessage.Headers.Add("Accept-Language", CultureInfo.CurrentCulture.ToString());

                var content = new FormUrlEncodedContent(new[]
                    {
                        new KeyValuePair<string, string>("q", "Test"),
                    });

                requestMessage.Content = content;
                try
                {
                    var response = client.SendAsync(requestMessage);
                    if (response.Result.IsSuccessStatusCode)
                    {
                        var responseContent = response.Result.Content;
                        string responseString = responseContent.ReadAsStringAsync().Result;

                        return (JContainer) JsonConvert.DeserializeObject(responseString);
                    }

                    return null;
                }
                catch (Exception e)
                {
                    return null;
                }
            }
        }

        private bool ServerCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }
```

**Comment by tedrog36** [comment]
I am getting the example same exception with my self signed certificate that works fine with default handler.  I would really like to use ModernHttpClient, it seems like a great solution.

I second the question above: Is there a property/parameter I need to set on the HttpClient side?

**Comment by geirsagberg** [comment]
According to [this commit](https://github.com/paulcbetts/ModernHttpClient/commit/3a7084cb5cde7783553099a29f26ff2c2ce77d4d), there is a parameter you need to pass into the constructor: `public NativeMessageHandler(bool throwOnCaptiveNetwork, bool customSSLVerification)`

**Comment by tedrog36** [comment]
@geirsagberg thanks, but I tried setting customSSLVerification but that did not help.

**Comment by paulcbetts** [comment]
Hi all - I've decided to make this a paid feature, please see http://log.paulbetts.org/modernhttpclient-pro-edition/ for more info

**Comment by PaulVipond** [comment]
@paulcbetts Hi, just to be clear on this. I'd like to use modernhttpclient with certificate pinning. Does ServicePointManager.ServerCertificateValidationCallback get called in either the free or paid version so I can validate the server certificate? If not, would you consider adding this as a feature if it's possible?
