### ISSUE TITLE
What pcl setting do i need 

### ISSUE THREAD

**Issue by HarryMcCarney** [paulcbetts/ModernHttpClient#47]
Hi Paul,

Trying to use this but keep getting errors on install into a pcl. Had the same problem today installing akavache.  https://github.com/akavache/Akavache/issues/126

What setting does the pcl need to target in order to install?

Install failed. Rolling back...
Install-Package : Could not install package 'modernhttpclient 1.2.2'. You are trying to 
install this package into a project that targets 
'portable-net45+wp80+win+MonoAndroid10+MonoTouch10', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more 
information, contact the package author.

**Comment by brendan-murphy** [comment]
Can you clarify what this means? "Just reference the Portable version of ModernHttpClient in your Portable Library." When I use ModernHttpClient in my PCL I get a JIT compiling error.

**Comment by Cheesebaron** [comment]
Add the ModernHttpClient nuget to your PCL and add it to your Xamarin.Android and Xamarin.iOS projects as well. That's it.
