### ISSUE TITLE
Support Client Certificates

### ISSUE THREAD

**Issue by rossdargan** [paulcbetts/ModernHttpClient#48]
This is quite a vague feature request as I'm not entirely sure what the best approach would be, but I want to access a web service secured via client certificates. 

I've started looking at implementing this on android, and  I think you probably need to add a KeyStore property to the OkHandler.

I haven't done any research into iOS yet. 

I'm hoping to do a pull request for this, but I'd be interested to know your thoughts on this.

**Comment by tofutim** [comment]
@rossdargan  did you ever get this working, I'm looking exactly for this.

**Comment by tofutim** [comment]
@paulcbetts I think this will become less and less niche over time as security becomes an issue. I vote for supporting it.

**Comment by tofutim** [comment]
@rossdargan For Windows 8 and phone, it is possible to switch from HttpClient to the Windows.Web version and use a filter to specify the ClientCertificate. For Desktop I also use WebRequestHandler.

**Comment by MWallenberg** [comment]
I'm looking for this functionality as well. Would be very glad to see it in ModernHttpClient.
