### ISSUE TITLE
NSUrlSessionHandler - using GZipStream causes IOException

### ISSUE THREAD

**Issue by jonathanpeppers** [paulcbetts/ModernHttpClient#50]
We are wanting to use this sweet library to talk with our web API server running on Azure. We support GZip requests, and I think `GZipStream` might expose a bug in `ByteArrayListStream`.

See my test project in a fork here: https://github.com/jonathanpeppers/ModernHttpClient/blob/i-heart-paul-betts/Tests.iOS/ModernHttpClientTests.cs

The `UseGZipLikeABoss` test fails when using `NSUrlSessionHandler`, but works with plain `HttpClientHandler`. You can change the declaration of `client` to see.

BTW, this might be another subject, but should there be a reasonable NUnit test project for iOS and Android anyway? Maybe I can help out with this, because we are wanting to use this thing in production apps at the company I work for.

**Comment by acaliaro** [comment]
Hi.
Can you give a "complete" example how to implement gzip in http?
Thanks

**Comment by Cheesebaron** [comment]
You don't have to do anything!

**Comment by acaliaro** [comment]
Wow Chhesebaron, we meet again.
Yes, I think to have understand.
(Your post from Xamarin Forum is just arrived... I feel surrounded)
Thanks

**Comment by Cheesebaron** [comment]
Read @paulcbetts answer.

If you try the httpbin, you will see that the result given is that the response was gzip encoded, and was magically decoded when you called it. No need to set any headers yourself.... 

I did something similar in a clean Android project:


```
using System.Net.Http;
using System.Threading.Tasks;
using Android.App;
using Android.Util;
using Android.Widget;
using Android.OS;
using ModernHttpClient;

namespace App23
{
    [Activity(Label = "App23", MainLauncher = true, Icon = "@drawable/icon")]
    public class MainActivity : Activity
    {
        int count = 1;

        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.Main);
            var button = FindViewById<Button>(Resource.Id.MyButton);
            button.Click += async delegate { await DoShit(); };
        }

        public async Task DoShit()
        {
            var client = new HttpClient(new NativeMessageHandler());

            var message = await client.GetAsync("http://httpbin.org/gzip").ConfigureAwait(false);

            if (message.IsSuccessStatusCode)
            {
                var str = await message.Content.ReadAsStringAsync().ConfigureAwait(false);
                Log.Debug("Woooow!", str);
            }
        }
    }
}
```

Gives me:


```
06-29 20:59:37.026 D/Woooow! ( 9429): {
06-29 20:59:37.026 D/Woooow! ( 9429):   "gzipped": true, 
06-29 20:59:37.026 D/Woooow! ( 9429):   "headers": {
06-29 20:59:37.026 D/Woooow! ( 9429):     "Accept-Encoding": "gzip", 
06-29 20:59:37.026 D/Woooow! ( 9429):     "Host": "httpbin.org", 
06-29 20:59:37.026 D/Woooow! ( 9429):     "User-Agent": "okhttp/2.3.0"
06-29 20:59:37.026 D/Woooow! ( 9429):   }, 
06-29 20:59:37.026 D/Woooow! ( 9429):   "method": "GET", 
06-29 20:59:37.026 D/Woooow! ( 9429):   "origin": "94.144.63.227"
06-29 20:59:37.026 D/Woooow! ( 9429): }
```

Which means gzip was used...

Still not convinced?

**Comment by acaliaro** [comment]
No I'm convenced. In Xamarin Forums there are some answers that send me out of road.
Thanks
