### ISSUE TITLE
Cancellation doesn't work on Android

### ISSUE THREAD

**Issue by guillaume-fr** [paulcbetts/ModernHttpClient#52]
This simple test fails

```
  var httpClient = new HttpClient(new ModernHttpClient.OkHttpNetworkHandler());
  CancellationToken ct = new CancellationToken(true); //Already cancelled
  try
  {
    await httpClient.GetAsync(@"http://www.google.com", ct);
    System.Diagnostics.Debugger.Break(); //HIT => Why ?
  }
  catch (OperationCanceledException)
  {
    //EXPECTED BUT NEVER HIT
  }
```

Same code in a WinForm project (with default HttpHandler) works as expected.

**Comment by predalpha** [comment]
Encountering that issue. CancellationToken does not work on Android
(if i remove new NativeMessageHandler() from the httpclient ctor, cancellationtoken works)

Visual Studio 2017 15.3.3
Xamarin 4.6.0.299
Xamarin Android SDK 7.4.0.21
*** Nuget ***
ModernHttpClient 2.4.2
Xamarin.Forms 2.3.4.270
