### ISSUE TITLE
ReasonPhrase not returned properly

### ISSUE THREAD

**Issue by pantelisk73** [paulcbetts/ModernHttpClient#64]
I have a ASP.NET MVC service that is returning an HttpStatusResult of 500 with a custom error phrase (Invalid User Name to be exact). When I use the NativeMessageHandler, the ReasonPhrase property of the HttpResponseMessage always shows "Internal Server Error" and never my status description.

If I comment out the use of the NativeMessageHandler, the vanilla handler that comes with the HttpClient does return the correct status description (as sent from the server).

Please advise :(

**Comment by marktaling** [comment]
Sadly the issue still exists in the iOS version :(
