### ISSUE TITLE
iOS custom SSL verification: create NSUrlCredential for completionHandler on success?

### ISSUE THREAD

**Issue by brendanzagaeski** [paulcbetts/ModernHttpClient#85]
For this line:

<pre><code><a href="https://github.com/paulcbetts/ModernHttpClient/blob/ca213af8020ed9dc05caa203f06dcebc7248d6bb/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs#L285">completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, null);</a></code></pre>

It looks like sending `null` to the `completionHandler` always leads to a "The certificate for this server is invalid" error.

If I change the line to create a credential from `challenge.ProtectionSpace.ServerSecTrust`, the validation succeeds:

```
completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, NSUrlCredential.FromTrust(challenge.ProtectionSpace.ServerSecTrust));
```

Hopefully this is the correct fix. I think it might be based on this:

> If you want to allow the connection, create a credential from your trust object (using +[NSURLCredential credentialForTrust:]) and call the completion handler block with that credential and the NSURLSessionAuthChallengeUseCredential disposition.

(from https://developer.apple.com/library/ios/technotes/tn2232/_index.html)

Many thanks for all your work on this library!

**Comment by amolsarmalkar** [comment]
We are getting NSUrlCredential as null despite of SecTrustResult.Proceed. It has HasPassword field as false. Debug screenshot of NSUrlCredential attached.

Finally in DidCompleteWithError we get a response with error saying inavild_grant (invalid username and password) . 
This happens on iOS11 and iOS 12 as well . 
What extra thing we need to do with sec trust object to get credentials from it. 

We are working on our production server. 

public override void DidReceiveChallenge(NSUrlSession session, NSUrlAuthenticationChallenge challenge, Action<NSUrlSessionAuthChallengeDisposition, NSUrlCredential> completionHandler)
{
    int i = 0;
    if (challenge.ProtectionSpace.AuthenticationMethod.Equals("NSURLAuthenticationMethodServerTrust"))
    {

        if (challenge.ProtectionSpace.Host.Equals("Our domain")
        {
            if (challenge.ProtectionSpace.ServerSecTrust == null)
            {
                completionHandler(NSUrlSessionAuthChallengeDisposition.PerformDefaultHandling, null);
            }
            else
            {
               

                NSData data = challenge.ProtectionSpace.ServerSecTrust.GetExceptions();
                bool added = challenge.ProtectionSpace.ServerSecTrust.SetExceptions(data);

                // challenge.ProtectionSpace.ServerSecTrust.GetTrustResult

                NSError error;
                bool passed = challenge.ProtectionSpace.ServerSecTrust.Evaluate(out error);
                SecTrustResult sResult = challenge.ProtectionSpace.ServerSecTrust.GetTrustResult();
                if (sResult == SecTrustResult.Proceed)
                {
                    NSUrlCredential urlcredential = NSUrlCredential.FromTrust(challenge.ProtectionSpace.ServerSecTrust);
                    completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, urlcredential);
                }
                else
                {
                    completionHandler(NSUrlSessionAuthChallengeDisposition.CancelAuthenticationChallenge, null);
                }




            }
        }
        else
        {
            completionHandler(NSUrlSessionAuthChallengeDisposition.PerformDefaultHandling, null);
        }

    }

![screen shot 2019-02-14 at 3 59 59 pm](https://user-images.githubusercontent.com/14293740/52783146-fff48580-3076-11e9-86e0-c87ebf074416.png)
