### ISSUE TITLE
Support for GZIP'ed response on Android

### ISSUE THREAD

**Issue by jorgenstorlie** [paulcbetts/ModernHttpClient#91]
I try to get a compressed response on Android o work.
It works on IOS without any additional code

like this

var httpClient = new HttpClient(new NativeMessageHandler());

but on Android it is not decompressed.

Must I do something more on Android?

(
Maybe some thing as this, nut not the same:
https://github.com/paulcbetts/ModernHttpClient/issues/35
https://github.com/paulcbetts/ModernHttpClient/issues/50
)

**Comment by chaozaiai** [comment]
Can you tell me Where do you change from deflate to gzip?
I will appreciate.
