### ISSUE TITLE
Multipart form-data boundary is missing from Content-type header

### ISSUE THREAD

**Issue by Qonstrukt** [paulcbetts/ModernHttpClient#92]
Something I'm noticing since the ModernHttpClient 2.x series is that the boundary is missing from the Content-type header when using Multipart form-data.

I'm using a derivate class from System.Net.Http.MultipartContent which has an optional boundary parameter in it's constructor. When this isn't set HttpClient generates one automatically. This boundary is then added between all the content parts, and added as a parameter to the Content-type like this:
`"multipart\/form-data; boundary=\"379dc741-a272-4441-b777-c892aa3cd45d\""`

The Content-type using ModernHttpClient looks like this:
`"multipart\/form-data"`

I've tried setting a boundary myself in the constructor of MultipartContent, but this doesn't make any difference.

When dumping Content.Headers.ContentType.ToString () from the request, it correctly outputs the header including the boundary, so it's kind of surprising it's missing from the actual request being sent. It's as if only the MediaType property is being sent, while the Parameters property is completely ignored.

**Comment by radhe12** [comment]
@rogihee could you please guide me on this "https://stackoverflow.com/users/8875271/radhey-g"
