### ISSUE TITLE
Custom SSL verification on Android does not work

### ISSUE THREAD

**Issue by sami1971** [paulcbetts/ModernHttpClient#99]
Creating a new HTTP client with native handler:

```
new HttpClient(new NativeMessageHandler(false, true));
```

Setting the SSL callback:

```
        System.Net.ServicePointManager.ServerCertificateValidationCallback +=
            (sender, cert, chain, sslPolicyErrors) => 
            {
                if (cert != null) System.Diagnostics.Debug.WriteLine(cert);
                return true;
            };
```

This works fine on iOS but Android does not call the callback and instead throws the SSLHandshakeException:

```
Exception of type 'Javax.Net.Ssl.SSLHandshakeException' was thrown.
```

**Comment by paulcbetts** [comment]
Hi all - I've decided to make self-signed certificates a paid feature, please see http://log.paulbetts.org/modernhttpclient-pro-edition/ for more info

**Comment by nberardi** [comment]
+1

Nick Berardi
(484) 302-0125
